# Generated by Django 4.0.3 on 2022-03-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
