# Generated by Django 4.0.3 on 2022-05-09 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0003_alter_products_image_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='aoooda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dsa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dsasacesc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('active', models.BooleanField(default=True)),
                ('review', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cat', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bestproduct.category')),
            ],
        ),
    ]
