# Generated by Django 4.0.3 on 2022-05-11 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0004_aoooda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bestproduct.category'),
        ),
        migrations.DeleteModel(
            name='aoooda',
        ),
    ]
