# Generated by Django 4.0.3 on 2022-05-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0005_alter_products_cat_delete_aoooda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='bestproduct.category'),
        ),
    ]
