# Generated by Django 4.0.3 on 2022-05-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0006_alter_products_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestproduct.category'),
        ),
    ]
