# Generated by Django 4.0.3 on 2022-05-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
