# Generated by Django 4.0.3 on 2022-05-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestproduct', '0009_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestproduct.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestproduct.customer')),
            ],
        ),
    ]
